### ISSUE TITLE
Serial to Reportr

### ISSUE THREAD

**Issue by chrigui** [Reportr/dashboard#64]
i have 2 arduino based sensor boards sending data over to a pi /dev/ttyAMA0 and i really like Reportr, Is it possible to create a plugin for Reportr Dashboard that can visualise sensor readings (Temperature, TempBMP, TempSHT, Pressure, Humidity, Dewpoint, Date, Pressure, Temperature, Altitude-at-Sea)
if yes any guidance on starting points please ?

**Comment by SamyPesse** [comment]
I would recommend you to write a program on your Pi to read data from sensors then post it as events using HTTP requests to reportr (on the same Pi or on a server).

**Comment by chrigui** [comment]
thank you i did exactly thank a friend of mine wrote a serial to mongodb, hopefully we can manage to grab this data to a locally installed Reportr..

Cheers
