### ISSUE TITLE
No new events added - Need: type

### ISSUE THREAD

**Issue by unnikked** [Reportr/dashboard#65]
I already searched before to post but I have found anything about my issue. 

I installed an instance of dashboard on a local virtual machine and everything works fine, I mean I can access to the web interface. 

But if I try to post a new event using the example snippet

```shell
curl -X POST --data '{ "type":"home.temperature", "properties": { "temperature": 66 } }' http://dashboard.local:5000/api/events
```

I get 

```
Need: type
```

I've also tried to set the environment variables (tested and worked login on the web interface), but when I tried to

```shell
curl -X POST --data '{ "type":"home.temperature", "properties": { "temperature": 66 } }' --user user:pass http://dashboard.local:5001/api/events
```

I get the same error message (changed the default port for testing)

```
Need: type
```

I'm deeply sorry if I asked a dumb question.

**Comment by SamyPesse** [comment]
This is not a dump question, don't worry ;)

I think the problem is that you need to sent a "Content-type" header to signal to the server that the body is JSON:

Can you try:

`curl -X POST -H "Accept: application/json" --data '{ "type":"home.temperature", "properties": { "temperature": 66 } }' http://dashboard.local:5000/api/events`

**Comment by unnikked** [comment]
As you suggested

```shell
 curl -X POST -H "Accept: application/json" --data '{ "type":"home.temperature", "properties": { "temperature": 66 } }' --user user:pass http://dashboard.local:5001/api/events
```

leads to: 

```json
{"error":"Need: type","code":500}
```

I've also tried adding `-H "X-Requested-With: XMLHttpRequest"` directive but it did not work.

Thank you for your quick response 😀

**Comment by SamyPesse** [comment]
Can you try:

`curl -X POST -F "type=test" --user user:pass http://dashboard.local:5001/api/events`

**Comment by unnikked** [comment]
I've solved the issue :smile: I used `-H "Content-Type: application/json"` directive header instead of the proposed one:

```shell
curl -X POST -H "Content-Type: application/json" --data '{ "type":"home.temperature", "properties": { "temperature": 66 } }' --user user:pass http://dashboard.local:5001/api/events
```

Response is

```json
{"posted":true}
```

I suggest you to update the README

**Comment by SamyPesse** [comment]
Perfect :+1:
